language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6

matrix:
  allow_failures:
    - compiler: clang
    - os: osx

before_install:
  # Setup cmake
  - sh scripts/install-cmake.sh

  # Prepare compilers
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then sh scripts/install-gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then sh scripts/install-clang.sh; fi

  # Debug information
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then lsb_release -a; fi
  - uname -a
  - $CC --version
  - $CXX --version

script:
  # Build with make
  - make clean
  - make

notifications:
  email: false

sudo: required

cache:
  - apt
